knp_snappy:
  pdf:
    enabled: true
    binary: 'C:\bin\wkhtmltopdf\bin\wkhtmltopdf.exe'
    options: []
  image:
    enabled: true
    binary: 'C:\bin\wkhtmltopdf\bin\wkhtmltoimage.exe'
    options: [ ]
